apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp-svc
  name: webapp-svc
spec:
  ports:
  - name: 8080-8080
    nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: webapp-deployment
  type: NodePort
status:
  loadBalancer: {}
